---
title: "Отток сотрудников компании"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(plotly)
library(crosstalk)
library(DBI)
library(tidymodels)
library(caret)
library(rsample)
```

```{r data, include=FALSE}
con <- dbConnect(ClickHouseHTTP::ClickHouseHTTP(), 
                 user='studentminor', 
                 password='DataMinorHSE!2023', 
                 dbname='employee', 
                 host='rc1a-i6ui9dhblsq8rgdo.mdb.yandexcloud.net',
                 port = 8443,
                 https=TRUE,
                 ssl_verifypeer=FALSE)

data = dbGetQuery(con, 'SELECT Gender, MaritalStatus, WorkLifeBalance,
                        Attrition, EnvironmentSatisfaction,
                        JobSatisfaction, MonthlyIncome,
                        OverTime, PercentSalaryHike, RelationshipSatisfaction
                        FROM portfolio 
                        INNER JOIN profile USING(EmployeeNumber)
                        WHERE Age <= 35')

data = data %>% mutate_if(is.character, as.factor)
data$Attrition = data$Attrition %>% as.factor()

#для графика
data_age = dbGetQuery(con, "SELECT Attrition, EnvironmentSatisfaction,
                        OverTime, Age
                        FROM portfolio 
                        INNER JOIN profile USING(EmployeeNumber)
                      WHERE Age <= 35")

data_age = data_age %>% mutate_if(is.character, as.factor)
data_age$Attrition = data_age$Attrition %>% as.factor()

data_a = data_age %>% group_by(Age) %>% summarise(count = n())

data_age = data_age %>% full_join(data_a)

lot = SharedData$new(data_age, group = "subset")
```

```{r model, include=FALSE}
#моделька
set.seed(134)
Split = initial_split(data, prop = 0.8)
train = training(Split)
test = testing(Split)
model = logistic_reg()


set.seed(134)
ds_up <- recipe(~., data = train) %>%
  themis::step_upsample(Attrition) %>% 
  prep(training = train, retain = TRUE) %>% 
  bake(new_data = NULL)

set.seed(134)
up_log_model = model %>% fit(Attrition ~., ds_up)

pred_up = predict(up_log_model, test)

#симуляция
test2 = test
set.seed(134)
test2$OverTime[test2$OverTime == "Yes"] = 
  sample(c("Yes", "No"), 
         size = length(test2$OverTime[test2$OverTime == "No"]),
         replace = T, prob = c(0.7, 0.3))
set.seed(134)
test2$EnvironmentSatisfaction[test2$EnvironmentSatisfaction == "Low"] = 
  sample(c("Low", "Medium", "High"), 
         size = 
      length(test2$EnvironmentSatisfaction[test2$EnvironmentSatisfaction == "Low"]),
         replace = T, prob = c(0.7, 0.2, 0.1))

pred_sim = predict(up_log_model, test2)
```

Параметры {.sidebar}
-------------------------------------

```{r}
filter_checkbox("OverTime", "Переработка", lot, ~OverTime)
filter_select("EnvironmentSatisfaction", "Уровень удовлетворённости рабочей средой", lot, ~EnvironmentSatisfaction)
filter_checkbox("Attrition", "Покинул ли сотрудник компанию?", lot, ~OverTime)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Распределение сотрудников по возрасту

```{r}
plot_ly(lot, x = ~Age, y = ~count, type = "bar")
```

## Column {data-width="350"}

### Процент оттока работников до 35 лет

```{r}
data1 = dbGetQuery(con, "SELECT Attrition, 
                        ROUND(COUNT(*)/(SELECT COUNT(*) FROM portfolio 
                                  INNER JOIN profile USING(EmployeeNumber)
                                  WHERE Age <=35)*100, 2) as prop 
                        FROM portfolio 
                        INNER JOIN profile USING(EmployeeNumber)
                        WHERE Age <= 35
                        GROUP BY Attrition")
dbDisconnect(con)

valueBox(round(data1$prop[data1$Attrition == 1],1), icon = "fa-percent")
```

### Факторы, влияющие на уход молодых кадров

```{r}
library(vip)
vip(up_log_model)
```

### Процент уменьшения оттока после введения изменений

```{r}
valueBox(round(((length(pred_up$.pred_class[pred_up$.pred_class == 1])/length(pred_up$.pred_class)) - (length(pred_sim$.pred_class[pred_sim$.pred_class == 1])/length(pred_sim$.pred_class)))*100, 1), icon = "fa-percent")
```
